### ISSUE TITLE
Transactions not storing

### ISSUE THREAD

**Issue by chrisharney** [codingchili/ethereum-ingest#7] opened 2018-02-07 00:57 UTC
Hey, cool project. I am getting an error on import, the blocks are being processed and stored properly but the transactions are failing. I am using the rinkeby network on geth and storing with MongoDB 3.6.2. My transaction collection is empty. Any help would be appreciated!

`ERROR   [00:38:43.744] failedTx        [TransactionService] java.lang.IllegalStateException: Unknown BsonType for '2'
	at io.vertx.ext.mongo.impl.codec.json.AbstractJsonCodec.writeValue(AbstractJsonCodec.java:83)
	at io.vertx.ext.mongo.impl.codec.json.AbstractJsonCodec.lambda$writeDocument$1(AbstractJsonCodec.java:261)
	at io.vertx.ext.mongo.impl.codec.json.JsonObjectCodec.lambda$forEach$0(JsonObjectCodec.java:116)
	at java.lang.Iterable.forEach(Unknown Source)
	at io.vertx.ext.mongo.impl.codec.json.JsonObjectCodec.forEach(JsonObjectCodec.java:115)
	at io.vertx.ext.mongo.impl.codec.json.JsonObjectCodec.forEach(JsonObjectCodec.java:23)
	at io.vertx.ext.mongo.impl.codec.json.AbstractJsonCodec.writeDocument(AbstractJsonCodec.java:258)
	at io.vertx.ext.mongo.impl.codec.json.AbstractJsonCodec.encode(AbstractJsonCodec.java:28)
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:63)
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:29)
	at com.mongodb.connection.UpdateCommandMessage.writeTheWrites(UpdateCommandMessage.java:85)
	at com.mongodb.connection.UpdateCommandMessage.writeTheWrites(UpdateCommandMessage.java:43)
	at com.mongodb.connection.BaseWriteCommandMessage.encodeMessageBodyWithMetadata(BaseWriteCommandMessage.java:129)
	at com.mongodb.connection.RequestMessage.encodeWithMetadata(RequestMessage.java:160)
	at com.mongodb.connection.WriteCommandProtocol.executeBatchesAsync(WriteCommandProtocol.java:150)
	at com.mongodb.connection.WriteCommandProtocol.executeAsync(WriteCommandProtocol.java:137)
	at com.mongodb.connection.UpdateCommandProtocol.executeAsync(UpdateCommandProtocol.java:76)
	at com.mongodb.connection.DefaultServer$DefaultServerProtocolExecutor.executeAsync(DefaultServer.java:179)
	at com.mongodb.connection.DefaultServerConnection.executeProtocolAsync(DefaultServerConnection.java:295)
	at com.mongodb.connection.DefaultServerConnection.updateCommandAsync(DefaultServerConnection.java:156)
	at com.mongodb.operation.MixedBulkWriteOperation$Run$6.executeWriteCommandProtocolAsync(MixedBulkWriteOperation.java:558)
	at com.mongodb.operation.MixedBulkWriteOperation$Run$AsyncRunExecutor.executeAsync(MixedBulkWriteOperation.java:703)
	at com.mongodb.operation.MixedBulkWriteOperation$Run.executeAsync(MixedBulkWriteOperation.java:423)
	at com.mongodb.operation.MixedBulkWriteOperation.executeRunsAsync(MixedBulkWriteOperation.java:230)
	at com.mongodb.operation.MixedBulkWriteOperation.access$600(MixedBulkWriteOperation.java:74)
	at com.mongodb.operation.MixedBulkWriteOperation$2$1.call(MixedBulkWriteOperation.java:212)
	at com.mongodb.operation.OperationHelper$3.call(OperationHelper.java:185)
	at com.mongodb.operation.OperationHelper.validateCollationAndWriteConcern(OperationHelper.java:140)
	at com.mongodb.operation.OperationHelper.validateWriteRequestCollations(OperationHelper.java:182)
	at com.mongodb.operation.OperationHelper$4.call(OperationHelper.java:205)
	at com.mongodb.operation.OperationHelper.checkBypassDocumentValidationIsSupported(OperationHelper.java:288)
	at com.mongodb.operation.OperationHelper.validateWriteRequests(OperationHelper.java:199)
	at com.mongodb.operation.MixedBulkWriteOperation$2.call(MixedBulkWriteOperation.java:204)
	at com.mongodb.operation.OperationHelper$8.onResult(OperationHelper.java:472)
	at com.mongodb.operation.OperationHelper$8.onResult(OperationHelper.java:465)
	at com.mongodb.connection.DefaultServer$1.onResult(DefaultServer.java:105)
	at com.mongodb.connection.DefaultServer$1.onResult(DefaultServer.java:96)
	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49)
	at com.mongodb.connection.DefaultConnectionPool.openAsync(DefaultConnectionPool.java:188)
	at com.mongodb.connection.DefaultConnectionPool.getAsync(DefaultConnectionPool.java:145)
	at com.mongodb.connection.DefaultServer.getConnectionAsync(DefaultServer.java:96)
	at com.mongodb.binding.AsyncClusterBinding$AsyncClusterBindingConnectionSource.getConnection(AsyncClusterBinding.java:102)
	at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:465)
	at com.mongodb.operation.OperationHelper.access$000(OperationHelper.java:58)
	at com.mongodb.operation.OperationHelper$AsyncCallableWithConnectionCallback.onResult(OperationHelper.java:459)
	at com.mongodb.operation.OperationHelper$AsyncCallableWithConnectionCallback.onResult(OperationHelper.java:449)
	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49)
	at com.mongodb.binding.AsyncClusterBinding$1.onResult(AsyncClusterBinding.java:81)
	at com.mongodb.binding.AsyncClusterBinding$1.onResult(AsyncClusterBinding.java:75)
	at com.mongodb.connection.BaseCluster$ServerSelectionRequest.onResult(BaseCluster.java:409)
	at com.mongodb.connection.BaseCluster.handleServerSelectionRequest(BaseCluster.java:280)
	at com.mongodb.connection.BaseCluster.selectServerAsync(BaseCluster.java:141)
	at com.mongodb.binding.AsyncClusterBinding.getAsyncClusterBindingConnectionSource(AsyncClusterBinding.java:75)
	at com.mongodb.binding.AsyncClusterBinding.getWriteConnectionSource(AsyncClusterBinding.java:70)
	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:438)
	at com.mongodb.operation.MixedBulkWriteOperation.executeAsync(MixedBulkWriteOperation.java:195)
	at com.mongodb.async.client.MongoClientImpl$2.execute(MongoClientImpl.java:140)
	at com.mongodb.async.client.MongoCollectionImpl.executeSingleWriteRequest(MongoCollectionImpl.java:623)
	at com.mongodb.async.client.MongoCollectionImpl.replaceOne(MongoCollectionImpl.java:393)
	at io.vertx.ext.mongo.impl.MongoClientImpl.replaceDocumentsWithOptions(MongoClientImpl.java:243)
	at com.codingchili.core.storage.MongoDBMap.put(MongoDBMap.java:81)
	at com.codingchili.ethereumingest.importer.TransactionService$1.onNext(TransactionService.java:92)
	at com.codingchili.ethereumingest.importer.TransactionService$1.onNext(TransactionService.java:70)
	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
	at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.slowPath(OnSubscribeFromIterable.java:117)
	at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.request(OnSubscribeFromIterable.java:89)
	at rx.Subscriber.setProducer(Subscriber.java:211)
	at rx.Subscriber.setProducer(Subscriber.java:205)
	at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:63)
	at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:34)
	at rx.Observable.subscribe(Observable.java:10238)
	at rx.Observable.subscribe(Observable.java:10205)
	at com.codingchili.ethereumingest.importer.TransactionService.importTx(TransactionService.java:70)
	at com.codingchili.ethereumingest.importer.TransactionService.lambda$null$0(TransactionService.java:58)
	at io.vertx.core.eventbus.impl.HandlerRegistration.deliver(HandlerRegistration.java:212)
	at io.vertx.core.eventbus.impl.HandlerRegistration.handle(HandlerRegistration.java:189)
	at io.vertx.core.eventbus.impl.EventBusImpl.lambda$deliverToHandler$3(EventBusImpl.java:538)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:344)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Unknown Source)
hash=0xd663f3920c6eb40b3d018c3583a9943732016961a024d3327f7e91113b608ce4
`

**Comment by codingchili** [comment] 2018-02-13 20:09
Hello!

Thanks for submitting an issue. I am very busy for the upcoming two weeks and will not be able to fix this. I'm guessing something changed in the API recently, last time i tested I was using geth 1.7.1. 

Also, sorry for the late reply, have been very busy the last week as well. :) 

Thanks for your patience, this will be my top priority when i get back!

**Comment by chrisharney** [comment] 2018-02-13 22:40
Thanks, no rush. 

Its having trouble with the nonce value. It throws `Unknown BsonType for '_nonce value here_' ` for each transaction.

**Comment by codingchili** [comment] 2018-03-21 20:51
Hello again,

I updated our web3j library to 3.3 and tested against ElasticSearch 6.2.3 and geth 1.8.2 without issues.

Is there a specific range of blocks you are having issues with? 

I tested with
  "startBlock" : "2022252",
  "blockEnd" : "2025555",

Changes are inclulded in the 1.0.2 release, let me know if you are still having issues.

Thanks!

**Comment by codingchili** [comment] 2018-03-22 12:25
Will verify with latest mongoDB as well. Updated the mongoDB connector version in 1.0.2.

**Comment by codingchili** [comment] 2018-07-14 19:36
unable to reproduce, closing for now.

**Closed as completed by codingchili** 2018-07-14 19:36 UTC
